print_status = printf "\033[1m[MAKE]: %s\033[0m\n"

all: install_pub_deps run_build_runner

install_pub_deps:
	@$(print_status) "Installing pub dependencies"
	flutter pub get

run_build_runner: install_pub_deps
	@$(print_status) "Running build_runner tool (for autogenerated code)"
	dart run build_runner build
