print_status = printf "\033[1m[MAKE]: %s\033[0m\n"

all: build_android

prep_dev: install_pub_deps gen_build_runner

# Install dependencies
install_pub_deps:
	@$(print_status) "Installing pub dependencies"
	flutter pub get

# Generate scaffolded code (isar database schemas)
gen_build_runner: install_pub_deps
	@$(print_status) "Running build_runner tool (for autogenerated code)"
	dart run build_runner build

# Generate app icons
gen_icons: install_pub_deps
	@$(print_status) "Running app icon generator tool"
	dart run flutter_launcher_icons

# Build android apk
build_android: clean gen_build_runner install_pub_deps
	@$(print_status) "Installing pub dependencies"
	flutter build apk --release

# Clean all cached files
clean:
	@$(print_status) "Cleaning caches"
	flutter clean