print_status = printf "\033[1m[MAKE]: %s\033[0m\n"

all: install

# Install dependencies
install_dependencies:
	@$(print_status) "Installing dependencies"
	flutter pub get

# Generate scaffolded code (isar database schemas)
run_code_gen_tools: install_dependencies
	@$(print_status) "Running build_runner tool (for autogenerated code)"
	dart run build_runner build

# Generate app icons
run_icons_gen_tools: install_dependencies
	@$(print_status) "Running app icon generator tool"
	dart run flutter_launcher_icons

# Build android apk
build_for_android: clean install_dependencies
	@$(print_status) "Installing pub dependencies"
	flutter build apk --release

# Build in release mode and install (already contains the build stage
# in the underlaying flutter command itself, so it is not needed here)
install:
	@$(print_status) "Installing on the connected device"
	flutter install

# Clean all cached files
clean:
	@$(print_status) "Cleaning project"
	flutter clean